name: omero-data-annotation
channels:
  - ome
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - omero-py  # ome
  - pip
  - scikit-image
  - pandas
  - numpy
  - pip:
    - omero-rois
    - omero-metadata
    - argh
